//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using EFDatabaseFirst.Data.POCOState;

namespace EFDatabaseFirst.Data.POCOEntities
{
    [MetadataType(typeof(BoatMetaData))]
    public partial class Boat : StateObject
    {
        #region Primitive Properties
    
    	public int Id
    	{
    		get;
    		set;
    	}
    
    	public string Name
    	{
    		get;
    		set;
    	}
    
    	public int ManufacturerId
    	{
    		get { return _manufacturerId; }
    		set
    		{
    			if (_manufacturerId != value)
    			{
    				if (Manufacturer != null && Manufacturer.Id != value)
    				{
    					Manufacturer = null;
    				}
    				_manufacturerId = value;
    			}
    		}
    	}
    	private int _manufacturerId;
    
    	public int Length
    	{
    		get;
    		set;
    	}
    
    	public bool Active
    	{
    		get;
    		set;
    	}
    
    	public System.DateTime ModifiedDt
    	{
    		get;
    		set;
    	}
    
    	public System.DateTime CreateDt
    	{
    		get;
    		set;
    	}

        #endregion
        #region Navigation Properties
    
    	public Manufacturer Manufacturer
    	{
    		get { return _manufacturer; }
    		set
    		{
    			if (!ReferenceEquals(_manufacturer, value))
    			{
    				var previousValue = _manufacturer;
    				_manufacturer = value;
    				FixupManufacturer(previousValue);
    			}
    		}
    	}
    	private Manufacturer _manufacturer;
    
    	public ICollection<Trip> Trips
    	{
    		get
    		{
    			if (_trips == null)
    			{
    				var newCollection = new FixupCollection<Trip>();
    				newCollection.CollectionChanged += FixupTrips;
    				_trips = newCollection;
    			}
    			return _trips;
    		}
    		set
    		{
    			if (!ReferenceEquals(_trips, value))
    			{
    				var previousValue = _trips as FixupCollection<Trip>;
    				if (previousValue != null)
    				{
    					previousValue.CollectionChanged -= FixupTrips;
    				}
    				_trips = value;
    				var newValue = value as FixupCollection<Trip>;
    				if (newValue != null)
    				{
    					newValue.CollectionChanged += FixupTrips;
    				}
    			}
    		}
    	}
    	private ICollection<Trip> _trips;

        #endregion
        #region Association Fixup
    
    	private void FixupManufacturer(Manufacturer previousValue)
    	{
    		if (previousValue != null && previousValue.Boats.Contains(this))
    		{
    			previousValue.Boats.Remove(this);
    		}
    
    		if (Manufacturer != null)
    		{
    			if (!Manufacturer.Boats.Contains(this))
    			{
    				Manufacturer.Boats.Add(this);
    			}
    			if (ManufacturerId != Manufacturer.Id)
    			{
    				ManufacturerId = Manufacturer.Id;
    			}
    		}
    	}
    
    	private void FixupTrips(object sender, NotifyCollectionChangedEventArgs e)
    	{
    		if (e.NewItems != null)
    		{
    			foreach (Trip item in e.NewItems)
    			{
    				item.Boat = this;
    			}
    		}
    
    		if (e.OldItems != null)
    		{
    			foreach (Trip item in e.OldItems)
    			{
    				if (ReferenceEquals(item.Boat, this))
    				{
    					item.Boat = null;
    				}
    			}
    		}
    	}

        #endregion
    }
}
