//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using EFDatabaseFirst.Data.POCOState;

namespace EFDatabaseFirst.Data.POCOEntities
{
    [MetadataType(typeof(CountryMetaData))]
    public partial class Country : StateObject
    {
        #region Primitive Properties
    
    	public int Id
    	{
    		get;
    		set;
    	}
    
    	public string Name
    	{
    		get;
    		set;
    	}

        #endregion
        #region Navigation Properties
    
    	public ICollection<State> States
    	{
    		get
    		{
    			if (_states == null)
    			{
    				var newCollection = new FixupCollection<State>();
    				newCollection.CollectionChanged += FixupStates;
    				_states = newCollection;
    			}
    			return _states;
    		}
    		set
    		{
    			if (!ReferenceEquals(_states, value))
    			{
    				var previousValue = _states as FixupCollection<State>;
    				if (previousValue != null)
    				{
    					previousValue.CollectionChanged -= FixupStates;
    				}
    				_states = value;
    				var newValue = value as FixupCollection<State>;
    				if (newValue != null)
    				{
    					newValue.CollectionChanged += FixupStates;
    				}
    			}
    		}
    	}
    	private ICollection<State> _states;

        #endregion
        #region Association Fixup
    
    	private void FixupStates(object sender, NotifyCollectionChangedEventArgs e)
    	{
    		if (e.NewItems != null)
    		{
    			foreach (State item in e.NewItems)
    			{
    				item.Country = this;
    			}
    		}
    
    		if (e.OldItems != null)
    		{
    			foreach (State item in e.OldItems)
    			{
    				if (ReferenceEquals(item.Country, this))
    				{
    					item.Country = null;
    				}
    			}
    		}
    	}

        #endregion
    }
}
